apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - flux-podmonitor.yaml
  - nginx-podmonitor.yaml
configMapGenerator:
  - name: flux-dashboards
    files:
      - ../../dashboards/control-plane.json
      - ../../dashboards/cluster.json
    options:
      labels:
        grafana_dashboard: "1"
