apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ingress-nginx
  namespace: prometheus
  labels:
    app.kubernetes.io/part-of: flagger
spec:
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  podMetricsEndpoints:
    - port: metrics
