prometheus:
  prometheusSpec:
    scrapeInterval: 5s
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}

grafana:
  adminPassword: gitopsyourlife
  sidecar:
    dashboards:
      searchNamespace: ALL
