prometheus:
  prometheusSpec:
    scrapeInterval: 5s
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}

grafana:
  adminPassword: gitops
  sidecar:
    dashboards:
      searchNamespace: ALL
