apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pypodinfo-staging
resources:
- namespace.yaml
- ../app
images:
- name: docker.io/steveww/pypodinfo
  newName: docker.io/steveww/pypodinfo # {"$imagepolicy": "flux-system:pypodinfo-staging:name"}
  newTag: Build-79 # {"$imagepolicy": "flux-system:pypodinfo-staging:tag"}
