version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  info:
    working_directory: /pypodinfo
    docker:
      - image: "docker:20"
    steps:
      - run:
          name: Dump Enviromment
          command: |
            env | sort
      - run:
          name: Tag info
          command: |
            echo "The Git tag is << pipeline.git.tag >>"
            echo "The Git branch is << pipeline.git.branch >>"
  
  build:
    working_directory: /pypodinfo
    docker:
      - image: "docker:20"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build \
            --cache-from=pypodinfo \
            --build-arg="VERSION=${CIRCLE_TAG:-Build-$CIRCLE_BUILD_NUM}" \
            -t pypodinfo \
            app
      - run:
          name: Push image to registry
          command: |
            TAG="${CIRCLE_TAG:-Build-$CIRCLE_BUILD_NUM}"
            docker login -u steveww -p $DOCKERHUB_PASSWD
            docker tag pypodinfo "steveww/pypodinfo:$TAG"
            docker push "steveww/pypodinfo:$TAG"

workflows:
  build_publish:
    jobs:
      - info
      - build:
          filters:
            branches:
              only: main
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
