{
 "title": "Flux Engine",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(workqueue_queue_duration_seconds_count{pod!=\"\"}, namespace)"
    }
   },
   {
    "name": "workers",
    "query": {
     "query": "label_values(workqueue_queue_duration_seconds_count{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "workers" },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$workers.*\"}[5m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$workers.*\"}[5m]))",
     "legendFormat": "Throttled"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$workers.*\",image!=\"\",container!=\"\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Work Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_queue_duration_seconds_sum{pod=~\"$workers.*\"}[5m])) / sum(rate(workqueue_queue_duration_seconds_count{pod=~\"$workers.*\"}[5m]))",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}