name: CircleCI
on:
  push:
    branches: ["main"]
    paths: ["app/**", ".circleci/config.yml"]

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
