name: CircleCI
on:
  push:
    branches: ["main"]
    paths: ["app/**"]

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: circleci/trigger_circleci_pipeline@v1.0.4
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
