name: Trusted Delivery

on:
  push:
    branches: [ "main", "flux-image-update" ]
    paths: [ "kustomize/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "kustomize/**" ]

jobs:
  kubeguard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: policy-check
        uses: magalixcorp/magalix-action@main
        with:
          webhook: ${{ secrets.KUBEGUARD_WEBHOOK }}
          directory: kustomize
