apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: pypodinfo-prod
  namespace: pypodinfo-prod
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pypodinfo
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: pypodinfo-prod
  
  # Rollout
  progressDeadlineSeconds: 600
  service:
    port: 8080
    targetPort: 8080
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
    
    # Make sure there is enough load for analysis
    webhooks:
      - name: load-test
        type: rollout
        url: http://flagger-loadtester.test/
        timeout: 5s
        metadata:
          cmd: "hey -z 2m -q 10 -c 2 http://pypodinfo-canary.pypodinfo-prod:8080/"