apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pypodinfo-prod
resources:
- namespace.yaml
- ../app
- canary.yaml
- ingress.yaml
images:
- name: docker.io/steveww/pypodinfo
  newName: docker.io/steveww/pypodinfo # {"$imagepolicy": "flux-system:pypodinfo-prod:name"}
  newTag: 1.0.4 # {"$imagepolicy": "flux-system:pypodinfo-prod:tag"}
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: pypodinfo
    spec:
      template:
        metadata:
          annotations:
            timestamp: "2022-03-18 15:33"
