apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: ingress-success-rate
spec:
  provider:
    type: prometheus
    address: http://ingress-nginx-flagger-prometheus.ingress-prometheus:9090
  query: |
    sum(rate(nginx_ingress_controller_requests{
      kubernetes_namespace="ingress-nginx",
      host="end2end.weave.works",
      canary!="",
      status!~"5.*"}[1m])) /
    sum(rate(nginx_ingress_controller_requests{
      kubernetes_namespace="ingress-nginx",
      host="end2end.weave.works",
      canary!=""}[1m])) * 100
